"""
Words that link a headline to a country.

Keys are the country ids used in data/world.json (ISO 3166 numeric codes).
Every country's own map name is matched automatically; add extra words here:
demonyms, capitals, big cities and a few well-known leaders.

Matching is case-sensitive and whole-word, and longer phrases win over shorter
ones ("South Sudan" is matched before "Sudan", "Northern Ireland" before "Ireland").

Edit freely. Leaders change, so review the leader names now and then.
"""

ALIASES = {
    # North America
    "840": ["U.S.", "US", "USA", "United States of America", "America", "Washington", "White House",
            "Pentagon", "Capitol Hill", "New York", "California", "Texas", "Florida", "Chicago",
            "Los Angeles", "New Mexico", "Hawaii", "Alaska"],
    "124": ["Canadian", "Canadians", "Ottawa", "Toronto", "Montreal", "Vancouver", "Quebec", "Alberta", "Carney"],
    "484": ["Mexican", "Mexicans", "Mexico City", "Sheinbaum", "Baja California", "Tijuana", "Guadalajara"],
    "304": ["Greenlandic", "Nuuk"],
    # Central America & Caribbean
    "192": ["Cuban", "Cubans", "Havana"],
    "332": ["Haitian", "Haitians", "Port-au-Prince"],
    "214": ["Dominican", "Santo Domingo"],
    "388": ["Jamaican"],
    "320": ["Guatemalan"],
    "340": ["Honduran", "Tegucigalpa"],
    "222": ["Salvadoran", "San Salvador", "Bukele"],
    "558": ["Nicaraguan", "Managua"],
    "188": ["Costa Rican", "San José"],
    "591": ["Panamanian", "Panama Canal"],
    "630": ["Puerto Rican", "San Juan"],
    # South America
    "076": ["Brazilian", "Brazilians", "Brasília", "Brasilia", "Rio de Janeiro", "São Paulo", "Sao Paulo", "Lula", "Bolsonaro"],
    "032": ["Argentine", "Argentinian", "Argentines", "Buenos Aires", "Milei"],
    "152": ["Chilean", "Chileans", "Santiago"],
    "170": ["Colombian", "Colombians", "Bogotá", "Bogota", "Medellín"],
    "862": ["Venezuelan", "Venezuelans", "Caracas", "Maduro"],
    "604": ["Peruvian", "Peruvians", "Lima"],
    "218": ["Ecuadorian", "Quito", "Guayaquil"],
    "068": ["Bolivian", "La Paz"],
    "600": ["Paraguayan", "Asunción"],
    "858": ["Uruguayan", "Montevideo"],
    "328": ["Guyanese"],
    # Europe
    "826": ["UK", "U.K.", "Britain", "British", "Great Britain", "England", "Scotland", "Scottish", "Wales", "Welsh",
            "Northern Ireland", "London", "Downing Street", "Westminster", "Manchester", "Liverpool", "Birmingham", "Starmer"],
    "372": ["Irish", "Dublin"],
    "250": ["French", "Paris", "Macron", "Élysée", "Marseille", "Lyon"],
    "276": ["German", "Germans", "Berlin", "Munich", "Hamburg", "Frankfurt", "Merz", "Bundestag"],
    "380": ["Italian", "Italians", "Rome", "Milan", "Naples", "Meloni", "Sicily"],
    "724": ["Spanish", "Madrid", "Barcelona", "Catalonia", "Sánchez"],
    "620": ["Portuguese", "Lisbon", "Porto"],
    "528": ["Dutch", "Amsterdam", "The Hague", "Rotterdam"],
    "056": ["Belgian", "Antwerp"],
    "756": ["Swiss", "Geneva", "Zurich", "Bern"],
    "040": ["Austrian", "Vienna"],
    "616": ["Polish", "Poles", "Warsaw", "Krakow"],
    "203": ["Czech Republic", "Czech", "Prague"],
    "703": ["Slovak", "Bratislava"],
    "348": ["Hungarian", "Hungarians", "Budapest", "Orbán", "Orban"],
    "642": ["Romanian", "Romanians", "Bucharest"],
    "100": ["Bulgarian", "Sofia"],
    "300": ["Greek", "Greeks", "Athens"],
    "688": ["Serbian", "Serbs", "Belgrade"],
    "191": ["Croatian", "Zagreb"],
    "705": ["Slovenian", "Ljubljana"],
    "070": ["Bosnia", "Bosnian", "Sarajevo"],
    "X-KOS": ["Kosovar", "Pristina"],
    "008": ["Albanian", "Tirana"],
    "807": ["Macedonian", "Skopje"],
    "499": ["Montenegrin", "Podgorica"],
    "804": ["Ukrainian", "Ukrainians", "Kyiv", "Kiev", "Kharkiv", "Odesa", "Odessa", "Lviv", "Donbas", "Crimea", "Zelensky", "Zelenskyy"],
    "643": ["Russian", "Russians", "Moscow", "Kremlin", "Putin", "St Petersburg", "St. Petersburg", "Siberia"],
    "112": ["Belarusian", "Minsk", "Lukashenko"],
    "498": ["Moldovan", "Chisinau", "Chișinău"],
    "440": ["Lithuanian", "Vilnius"],
    "428": ["Latvian", "Riga"],
    "233": ["Estonian", "Tallinn"],
    "246": ["Finnish", "Finns", "Helsinki"],
    "752": ["Swedish", "Swedes", "Stockholm"],
    "578": ["Norwegian", "Oslo"],
    "208": ["Danish", "Danes", "Copenhagen"],
    "352": ["Icelandic", "Reykjavik"],
    "196": ["Cypriot", "Nicosia"],
    # Middle East
    "792": ["Türkiye", "Turkish", "Turks", "Ankara", "Istanbul", "Erdogan", "Erdoğan"],
    "376": ["Israeli", "Israelis", "Jerusalem", "Tel Aviv", "Netanyahu", "IDF"],
    "275": ["Palestinian", "Palestinians", "Gaza", "West Bank", "Ramallah", "Hamas"],
    "422": ["Lebanese", "Beirut", "Hezbollah"],
    "760": ["Syrian", "Syrians", "Damascus", "Aleppo"],
    "400": ["Jordanian", "Amman"],
    "368": ["Iraqi", "Iraqis", "Baghdad", "Mosul", "Erbil"],
    "364": ["Iranian", "Iranians", "Tehran", "Strait of Hormuz", "Hormuz"],
    "682": ["Saudi", "Saudis", "Riyadh", "Jeddah", "Mecca"],
    "887": ["Yemeni", "Yemenis", "Sanaa", "Houthi", "Houthis", "Aden"],
    "512": ["Omani", "Muscat"],
    "784": ["UAE", "U.A.E.", "Emirati", "Dubai", "Abu Dhabi"],
    "634": ["Qatari", "Doha"],
    "414": ["Kuwaiti"],
    # Africa
    "818": ["Egyptian", "Egyptians", "Cairo", "Sisi"],
    "434": ["Libyan", "Tripoli", "Benghazi"],
    "788": ["Tunisian", "Tunis"],
    "012": ["Algerian", "Algiers"],
    "504": ["Moroccan", "Rabat", "Casablanca"],
    "729": ["Sudanese", "Khartoum", "Darfur"],
    "728": ["South Sudanese", "Juba"],
    "231": ["Ethiopian", "Ethiopians", "Addis Ababa", "Tigray"],
    "232": ["Eritrean", "Asmara"],
    "706": ["Somali", "Mogadishu", "al-Shabab", "Al-Shabaab"],
    "X-SOL": ["Hargeisa"],
    "404": ["Kenyan", "Kenyans", "Nairobi", "Mombasa"],
    "800": ["Ugandan", "Kampala"],
    "834": ["Tanzanian", "Dar es Salaam", "Dodoma", "Zanzibar"],
    "646": ["Rwandan", "Kigali"],
    "108": ["Burundian", "Bujumbura"],
    "180": ["DRC", "DR Congo", "Democratic Republic of Congo", "Democratic Republic of the Congo", "Congolese", "Kinshasa", "Goma", "Congo"],
    "178": ["Congo-Brazzaville", "Republic of Congo", "Brazzaville"],
    "566": ["Nigerian", "Nigerians", "Lagos", "Abuja"],
    "562": ["Nigerien", "Niamey"],
    "288": ["Ghanaian", "Accra"],
    "384": ["Ivory Coast", "Ivorian", "Abidjan"],
    "686": ["Senegalese", "Dakar"],
    "466": ["Malian", "Bamako"],
    "854": ["Burkinabe", "Ouagadougou"],
    "148": ["Chadian", "N'Djamena"],
    "120": ["Cameroonian", "Yaoundé", "Douala"],
    "140": ["Bangui"],
    "024": ["Angolan", "Luanda"],
    "894": ["Zambian", "Lusaka"],
    "716": ["Zimbabwean", "Harare"],
    "508": ["Mozambican", "Maputo"],
    "454": ["Malawian", "Lilongwe"],
    "450": ["Malagasy", "Antananarivo"],
    "710": ["South African", "South Africans", "Johannesburg", "Cape Town", "Pretoria", "Durban", "Ramaphosa"],
    "516": ["Namibian", "Windhoek"],
    "072": ["Botswanan", "Gaborone"],
    "430": ["Liberian", "Monrovia"],
    "694": ["Sierra Leonean", "Freetown"],
    "324": ["Guinean", "Conakry"],
    # Asia
    "156": ["Chinese", "Beijing", "Shanghai", "Hong Kong", "Shenzhen", "Xinjiang", "Tibet", "Xi Jinping"],
    "158": ["Taiwanese", "Taipei"],
    "392": ["Japanese", "Tokyo", "Osaka", "Okinawa"],
    "410": ["South Korean", "South Koreans", "Seoul", "Busan"],
    "408": ["North Korean", "North Koreans", "Pyongyang", "Kim Jong Un"],
    "496": ["Mongolian", "Ulaanbaatar"],
    "356": ["Indian", "Indians", "New Delhi", "Delhi", "Mumbai", "Kolkata", "Chennai", "Bengaluru", "Bangalore", "Kashmir", "Modi"],
    "586": ["Pakistani", "Pakistanis", "Islamabad", "Karachi", "Lahore"],
    "004": ["Afghan", "Afghans", "Kabul", "Taliban"],
    "050": ["Bangladeshi", "Dhaka"],
    "144": ["Sri Lankan", "Colombo"],
    "524": ["Nepali", "Nepalese", "Kathmandu"],
    "104": ["Burma", "Burmese", "Yangon", "Naypyidaw"],
    "764": ["Thai", "Bangkok"],
    "116": ["Cambodian", "Phnom Penh"],
    "418": ["Lao", "Laotian", "Vientiane"],
    "704": ["Viet Nam", "Vietnamese", "Hanoi", "Ho Chi Minh City"],
    "608": ["Philippine", "Filipino", "Filipinos", "Manila", "Mindanao"],
    "458": ["Malaysian", "Kuala Lumpur"],
    "360": ["Indonesian", "Indonesians", "Jakarta", "Bali", "Java", "Sumatra"],
    "626": ["East Timor", "Timorese", "Dili"],
    "398": ["Kazakh", "Astana", "Almaty"],
    "860": ["Uzbek", "Tashkent"],
    "417": ["Kyrgyz", "Bishkek"],
    "762": ["Tajik", "Dushanbe"],
    "795": ["Turkmen", "Ashgabat"],
    "051": ["Armenian", "Armenians", "Yerevan"],
    "031": ["Azerbaijani", "Baku"],
    "268": ["Tbilisi"],
    # Oceania
    "036": ["Australian", "Australians", "Canberra", "Sydney", "Melbourne", "Brisbane", "Perth", "Queensland"],
    "554": ["New Zealander", "Auckland", "Christchurch"],
    "598": ["Port Moresby"],
    "242": ["Fijian", "Suva"],
}

# Phrases that should NOT count for any country. They are matched first and
# then ignored, which stops "Latin America" from being read as "America".
IGNORE = [
    "Latin America", "Latin American", "South America", "South American", "Central America",
    "Central American", "North America", "North American", "American Samoa", "Indian Ocean",
    "Korean Peninsula", "Gulf of Mexico", "Gulf of America", "New Jersey", "New England",
    "Native American", "Captain America", "Paris Hilton", "Jordan Peterson", "Michael Jordan",
    "Chad Smith", "Georgia O'Keeffe", "Turkey Day",
]

# Map names that are too ambiguous to match on their own. The aliases above
# still apply (e.g. Georgia the country is matched through "Tbilisi").
SKIP_MAP_NAME = {"268", "400", "178"}   # Georgia (US state), Jordan (first name), bare "Congo" goes to DR Congo
